uint32 TYPE_HEAD           = 0
uint32 TYPE_NECK           = 1
uint32 TYPE_LEFT_SHOULDER  = 2
uint32 TYPE_RIGHT_SHOULDER = 3
uint32 TYPE_LEFT_ELBOW     = 4
uint32 TYPE_RIGHT_ELBOW    = 5
uint32 TYPE_LEFT_HAND      = 6
uint32 TYPE_RIGHT_HAND     = 7
uint32 TYPE_TORSO          = 8
uint32 TYPE_LEFT_HIP       = 9
uint32 TYPE_RIGHT_HIP      = 10
uint32 TYPE_LEFT_KNEE      = 11
uint32 TYPE_RIGHT_KNEE     = 12
uint32 TYPE_LEFT_FOOT      = 13
uint32 TYPE_RIGHT_FOOT     = 14
uint32 TYPE_ROOT           = 15

uint32 type

geometry_msgs/Point position
geometry_msgs/Quaternion orientation

float64 position_confidence
float64 orientation_confidence
